### ISSUE TITLE
This is possible with torrest?

### ISSUE THREAD

**Issue by BTopbas** [i96751414/plugin.video.torrest#1]
I have Apple TV and run Kodi on it. But Apple TV don't support the binary run. So maybe this client and server idea will work.
Server can be raspberry pi or Linux or windows
Client is kodi addon simple python not run binary

Here is another user schema. I like it but elementum not support it and development stop. Maybe Torrest take flag from elementum? Why not?

![image](https://user-images.githubusercontent.com/496793/42570912-188b194c-851e-11e8-8411-6c035032a7cf.png)

**Comment by i96751414** [comment]
All the code is written to support python 3 (Kodi 19). However, the way things are currently, it is not possible to have one version supporting both Kodi <= 18 and Kodi >= 19. At some point I will start supporting Kodi 19+ only, but I would like to wait a bit.

I never tested the binary in Mac, so it would be great if you could test it :)
You can either install this addon through the [virtual repo](https://github.com/i96751414/repository.github) or download the [binary ](https://github.com/i96751414/torrest/releases/tag/v0.0.2)and run it on the command line.

**Comment by BTopbas** [comment]
I tested binary and works like a charm!

![Screen Shot 2020-05-29 at 21 46 51](https://user-images.githubusercontent.com/6390054/83294746-7ed2ea80-a1f6-11ea-8e67-2a431f2fca6b.png)

I added .torrent file in local web UI and execute. Automatically created Torrents folder near binary file inside this folder have .torrent and .fastresume files. I check the torrent status on swagger UI 
Here is output:

```
[
  {
    "info_hash": "dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c",
    "name": "Big Buck Bunny",
    "size": 276445467,
    "status": {
      "total": 276445467,
      "total_done": 0,
      "total_wanted": 0,
      "total_wanted_done": 0,
      "progress": 100,
      "download_rate": 0,
      "upload_rate": 0,
      "paused": false,
      "has_metadata": true,
      "state": 4,
      "seeders": 0,
      "seeders_total": 25,
      "peers": 1,
      "peers_total": 2,
      "seeding_time": 0,
      "finished_time": 227,
      "active_time": 228,
      "all_time_download": 0,
      "all_time_upload": 0
    }
  }
]
```
After that execute /torrents/{infoHash}/download command and Big Buck Bunny folder and files created near binary.

All is well!

**Comment by BTopbas** [comment]
Today I figure out how to client and server method. I removed some codes in service.py (DaemonMonitor class) and changed IP in navigation.py api = Torrest("127.0.0.1", get_port()) to server IP. also set port in addon settings. And it worked. Torrest server in my mac and addon in apple tv I can add torrent and stream media. Woohoo!

Today I saw your other addon Flix. Flix can work with torrest? May be compatible with elementum burst?

I like these new addons. And I have a few feature requests. 

Old times we have script.subscription services on IMDB and trakt.tv .(lists trendings etc.) 
This script automatically adds new items to the library every 6 or 12 hours. (selectable in settings)
In your flix addon we go item and select add library this is work but I wish this automate setting in settings. the addon has trending, popular lists also category. so it can check these lists and add every new item automatically to the library.

And after that in the library, we click item and item calls burst addon and select the torrent then torrent goes torrest server and serve playable media automatically. So this method every device can use this addon like Apple TV. 

If you want to look I can send zip of old subscription addons.

**Comment by i96751414** [comment]
Nice! I'm working on that at the moment, so it should work out of the box soon.

"Flix can work with torrest?" - Yep. Flix can actually work with everything, it was made so it could work with any kind of providers (torrents, movie sites like netflix), it is just a question of developing the provider. I can help in regards providers, but I will not provide any illegal one.

Regarding the library, I like your ideas and it is a work in progress (it was recently added to flix - not yet released). In the future I will add automatic updates and automatic reloading to library integration.

Just a note - please feel free to do any PRs if you want. All the help is welcome

**Comment by BTopbas** [comment]
I am a beginner in python and Kodi addons. Not so much experience. But I can do what I can. 
I can buy you a beer if you have Paypal :)

Today I tried master branch and only one little error happened. This error does not prevent the plugin from running but has an easy fix.
https://github.com/i96751414/plugin.video.torrest/blob/master/lib/service.py#L32 
in this line we don't need to check exec permissions when running remote binary. If this line enabled we have error like this

`OSError: [Errno 2] No such file or directory: '/storage/.kodi/addons/plugin.video.torrest/resources/bin/linux_armv7/torrest'
`

Solution is if torrest service disabled don't run exec permission else run exec permission.

**Comment by i96751414** [comment]
The commit closed this automatically. I believe all is good now. Thanks for raising it!

**Comment by BTopbas** [comment]
Yep. All is well! 
But another problem happened today. I don't know why and I am searching problem source. When adding .torrent no problem but adding magnet link cant create torrent file in Torrents folder. Morning this is working and now I can only add .torrent file. I try to add magnet on addon also local web UI but failed both. I think something wrong server binary or setting.

**Comment by i96751414** [comment]
I added a magnet and it worked well... If you are still having the error, can you please open a new issue with logs?

**Comment by BTopbas** [comment]
I don't know why but it looks like bittorrent stopped working on mac. 
I install Linux version of torrest on raspberry pi all is working well. I noticed after that in Linux:

![Screen Shot 2020-05-31 at 16 28 43](https://user-images.githubusercontent.com/6390054/83353574-3b928c00-a35c-11ea-896a-4946cd6c802d.png)

we have INFO bittorrent lines when starting.
But on MacBook, these lines not coming. I restarted mac, restarted network, try different directories, redownload the torrest, but no success. 

![Screen Shot 2020-05-31 at 16 28 52](https://user-images.githubusercontent.com/6390054/83353585-45b48a80-a35c-11ea-8c0c-4f772044eed6.png)

Weird

**Comment by i96751414** [comment]
That's expected. It only adds the torrent, then you have to manually start the download. It could be configurable though.

Regarding the logs missing, it is strange... I will have a look.

**Comment by i96751414** [comment]
I believe you might have changed the service loglevel. Can you show what are your current settings? You can get then through swagger

**Comment by BTopbas** [comment]
Solved!
I tried play settings in swagger and when you click set settings these example settings loaded. And i changed values on these settings. 
```
{
  "alerts_log_level": 0,
  "buffer_size": 20971520,
  "connections_limit": 0,
  "disable_dht": false,
  "disable_upnp": false,
  "download_path": "downloads",
  "encryption_policy": 0,
  "limit_after_buffering": false,
  "listen_interfaces": "string",
  "listen_port": 6889,
  "max_download_rate": 0,
  "max_upload_rate": 0,
  "outgoing_interfaces": "string",
  "proxy": {
    "hostname": "string",
    "password": "string",
    "port": 0,
    "type": 0,
    "username": "string"
  },
  "seed_time_limit": 0,
  "seed_time_ratio_limit": 0,
  "service_log_level": 0,
  "session_save": 30,
  "share_ratio_limit": 0,
  "torrents_path": "downloads/Torrents",
  "tuned_storage": false,
  "user_agent": 0
}
```
After your comment, I get settings on raspberry and copy and set mac via swagger. Now everything works.
This is very weird cause I redownload torrest another folder then unzip and run inside this folder use same broken settings.. 

Now mac and raspi server works great!

**Comment by i96751414** [comment]
`"alerts_log_level": 0` is CRITICAL log level, that's why you are not seeing those log entries. If you set it to the default value (4 - INFO) you should be able to see it again :)
