### ISSUE TITLE
Torrest binary would crash if not accesible download path

### ISSUE THREAD

**Issue by lopezvg** [i96751414/plugin.video.torrest#11]
If for any reason the user sets an un-accesible download path (in-existent, read-only, ...) Torrest binary would crash.  It will not recover on Kodi init:

`2021-03-14 22:23:28.385 T:4564  NOTICE: [plugin.video.torrest] Starting daemon with args: ('-port', '61235', '-settings', u'C:\\Users\\Rober\\AppData\\Roaming\\Kodi\\userdata\\addon_data\\plugin.video.torrest\\settings.json')
2021-03-14 22:23:31.654 T:4564  NOTICE: [plugin.video.torrest] Starting daemon logger
2021-03-14 22:23:31.755 T:12504  NOTICE: [plugin.video.torrest] [main] main - Loading configs
2021-03-14 22:23:31.774 T:12504  NOTICE: [plugin.video.torrest] [main] main - Starting bittorrent service
2021-03-14 22:23:31.775 T:12504  NOTICE: [plugin.video.torrest] panic: Unable to create 'downloads' folder: mkdir downloads: El sistema no puede encontrar la ruta especificada.
2021-03-14 22:23:31.776 T:12504  NOTICE: [plugin.video.torrest]
2021-03-14 22:23:31.787 T:12504  NOTICE: [plugin.video.torrest] goroutine 1 [running]:
2021-03-14 22:23:31.788 T:12504  NOTICE: [plugin.video.torrest] github.com/i96751414/torrest/bittorrent.createDir(0x1c60503, 0x9)
2021-03-14 22:23:31.788 T:12504  NOTICE: [plugin.video.torrest] 	/go/src/github.com/i96751414/torrest/bittorrent/utils.go:20 +0x14b
2021-03-14 22:23:31.789 T:12504  NOTICE: [plugin.video.torrest] github.com/i96751414/torrest/bittorrent.NewService(0xc000390240, 0x4)
2021-03-14 22:23:31.790 T:12504  NOTICE: [plugin.video.torrest] 	/go/src/github.com/i96751414/torrest/bittorrent/service.go:88 +0x43
2021-03-14 22:23:31.791 T:12504  NOTICE: [plugin.video.torrest] main.main()
2021-03-14 22:23:31.791 T:12504  NOTICE: [plugin.video.torrest] 	/go/src/github.com/i96751414/torrest/main.go:54 +0x66d`

In this case, the binary should find an alternative accesible default path, but not crash.  /userdata/addon_data/plugin.video/torrest would be a good place, not only for the python part, but also for the binary.

In the current situation, if not settings.json exists, the binary uses the exec binary path as default for download and torrent path.  It may happens, mainly in Android 10+, that that path is read-only
[LOG304516937.log](https://github.com/i96751414/plugin.video.torrest/files/6142924/LOG304516937.log)

**Comment by i96751414** [comment]
The binary is completely agnostic to kodi paths. The rationale is that the binary should be able to run without kodi. So having a default accessible (kodi) path is not an option.

In fact, making it crash is the correct solution, as this way the user must define a valid path in order to use the daemon.

However, I agree that if the user sets a valid path and then somehow he makes the path not valid, the settings.json will always contain an invalid path and the binary will not start - maybe in this case we can invalidate the old settings.json.

**Comment by lopezvg** [comment]
Ok

**Comment by lopezvg** [comment]
I've been thinking about this issue.  I think the binary should do something as well.  If a path to the settings.json is passed in the binary call, that path should be used by default to create the download and torrent folders, either y theer is no settings.json, or the download and torrent paths are inaccesible.

**Comment by i96751414** [comment]
I think I didn't understand the whole idea.

Atm, the binary has a default path (which is relative to the binary location). However, if a path is specified in settings.json, it will use that path. The changes I made (on binary side) will only let one to modify that path if it is valid.

**Comment by lopezvg** [comment]
I understand "_the binary has a default path (which is relative to the binary location)_"  However, still in the initial load, right after the installation, the settings.json file path is supplied with the binary call (typically '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.torrest/settings.json'), but the settings.json file does not exists.  So the binary takes as default path the relative path of the binary location.

It has two side effects: 
- It writes folders/files in the system partition, which in non-rooted devices it will be inaccessible to the normal user
- In Android 10+, if an app is needed to assist on launching the binary, that folder will be read-only 

Additionally, at least before your latest changes, if the paths download and torrents inside settings.json are inaccessible, it tries to use the path relative to the binary location as default, where we face the issues described above.

That is the reason I suggest to use the settings.json file path, if supplied, as default folder for the binary use, in case the settings.json file does not exists or the download and torrents paths supplied inside the .json are not valid.

**Comment by i96751414** [comment]
Ahh, I see what you mean. Let me correct something: when I said "which is relative to the binary location" I made an incorrect statement. It is, in fact, relative to the current working directory.

So it is a matter of using the correct working directory when starting the binary, right?

This can be achieved in both python and java/kotlin. You just need to set the correct cwd (which will then be the default path of torrents/download folder).

**Comment by lopezvg** [comment]
Fully agree.  I found it yesterday just by chance!

The point I am trying to make is that if the call is providing the binary with the folder for the settings.json file, the binary should take it as a "cwd" default path.

That would save the callers from some headaches...
