### ISSUE TITLE
Torrest daemon dont start on android tv so

### ISSUE THREAD

**Issue by mecoolk6** [i96751414/plugin.video.torrest#12]
I have mecoolk6 with original android tv 10, im using kodi 19 matrix and install torrest from github repo, instalation dont give me an error but daemon look like dont start, when i use it under windows 10, i dont have any problem working on same kodi version.

Thanks

**Comment by i96751414** [comment]
Hi. This is related to Kodi 19 being compiled against sdk29. This has restrictions when it comes to running binaries in Android 10. At the moment only rooted devices are supported for Kodi 19+, however a solution is being implemented.

**Comment by i96751414** [comment]
Hi. [v0.0.15](https://github.com/i96751414/plugin.video.torrest/releases/tag/v0.0.15) released today - Android devices should now be supported again.
