### ISSUE TITLE
Torrest deamon does not start on CoreElec

### ISSUE THREAD

**Issue by lopezvg** [i96751414/plugin.video.torrest#13]
CoreElec 9.2.7, arm7,  Kodi 18.9.

After automatic update to v.0.0.11 deamon would not start after several retries.

Attached Kodi log with debug activated
[kodi.log](https://github.com/i96751414/plugin.video.torrest/files/6267231/kodi.log)

**Comment by i96751414** [comment]
Thank you for the log. Unfortunately I had to update armv7 and arm64 toolchains, hence the fail. I will have a look and produce a new binary when I have some spare time.

**Comment by i96751414** [comment]
Can you send me the crashlog on userdata/addon_data/plugin.video.torrest?

**Comment by lopezvg** [comment]
I am afraid they are completely empty

**Comment by i96751414** [comment]
Ok. During the weekend I will rebuild the binary with the old toolchain and then send it to you. If it works I guess we will revert the toolchain (though I am not sure for how long)

**Comment by lopezvg** [comment]
Ok.  Just to be sure, the problem occurs just in Linux arm/arm64.  In Android arm/arm64 it works perfect

**Comment by i96751414** [comment]
Ohh. You previously said armv7. I’ll have a look into arm64 toolchain as well.

**Comment by lopezvg** [comment]
To be honest I have seen the problem only in arm (I have no arm64 hw to check), but I think it would be wise to check also the arm64 binary

**Comment by i96751414** [comment]
What is the name of the folder containing the binary (inside the plugin folder)?

**Comment by lopezvg** [comment]
linux_armv7

**Comment by i96751414** [comment]
Can you try with this binary? Note this is the binary only. If you want to test with the plugin, you will have to manually place it into the plugin folder.

[torrest.zip](https://github.com/i96751414/plugin.video.torrest/files/6289690/torrest.zip)

**Comment by lopezvg** [comment]
Now it works fine

**Comment by i96751414** [comment]
Nice. I will revert to the old toolchain for now.
