### ISSUE TITLE
Kodi 19.1 crashes Torrest on RPi 4 with LibreELEC (official): 9.95.4 10.0

### ISSUE THREAD

**Issue by lopezvg** [i96751414/plugin.video.torrest#15]
User claims the environment was working fine with previous LibreELEC and Kodi 18.9 versions
[LibreElect 9.95.4 Kodi 19.1 - Torrest-Kodi crash.log](https://github.com/i96751414/plugin.video.torrest/files/6832976/LibreElect.9.95.4.Kodi.19.1.-.Torrest-Kodi.crash.log)

**Comment by i96751414** [comment]
Hi! Thank you for reporting this. Unfortunately I don't have how to test this with a different image. So this will probably need some time until someone is able to solve this.

**Comment by i96751414** [comment]
This seems to happen here: https://github.com/i96751414/torrest/blob/v0.0.8/bittorrent/service.go#L651

Can the user delete the resume data of this torrent and try again?

**Comment by lopezvg** [comment]
The user has update LibreELEC to the latest (beta) version.  Now it seems he's able to download some torrents properly.  However he has have a Kodi reinitialization after several tries, but the log does not reflect any particular problem.

If you agree, let's leave this issue opened for some few days in case the user is able to supply additional meaningful documentation, otherwise, please close it.
