### ISSUE TITLE
Kodi 20 compatibility

### ISSUE THREAD

**Issue by lopezvg** [i96751414/plugin.video.torrest#18]
File "E:\Program Files\Kodi_20\Kodi\portable_data\addons\plugin.video.torrest\lib\dialog.py", line 1, in <module>
                                                       from xbmcgui import Dialog, WindowXMLDialog, ACTION_PARENT_DIR, ACTION_NAV_BACK, ACTION_PREVIOUS_MENU
                                                   ImportError: cannot import name 'ACTION_PARENT_DIR' from 'xbmcgui' (unknown location)
                                                   -->End of Python script error report<--

Please, take a look to this alternative code:

try:
    from xbmcgui import Dialog, WindowXMLDialog, ACTION_PARENT_DIR, ACTION_NAV_BACK, ACTION_PREVIOUS_MENU
except:
    #CHECK https://github.com/xbmc/xbmc/input/actions/ActionIDs.h
    from xbmcgui import Dialog, WindowXMLDialog
    ACTION_PARENT_DIR = 9
    ACTION_NAV_BACK = 92
    ACTION_PREVIOUS_MENU = 10

**Comment by i96751414** [comment]
This was already fixed in https://github.com/xbmc/xbmc/pull/21392 - hence no need to update the code for this.
You can either use a nightly version or wait for a beta (or stable) version of Kodi 20.

**Comment by lopezvg** [comment]
You are right.  Thanks
