### ISSUE TITLE
Error while loading shared libraries: libatomic.so.1 in Libreelec and Coreelec on Torrest version 0.0.13

### ISSUE THREAD

**Issue by lopezvg** [i96751414/plugin.video.torrest#19]
```
Starting Kodi (19.4 (19.4.0) Git:19.4-Matrix). Platform: Linux ARM 32-bit
INFO <general>: Using Release Kodi x32
INFO <general>: Kodi compiled 2022-03-05 by GCC 10.2.0 for Linux ARM 32-bit version 5.10.95 (330335)
INFO <general>: Running on BCM2835 with **LibreELEC** (official): 10.0.2, kernel: Linux ARM 64-bit version 5.10.95
INFO <general>: FFmpeg version/source: 4.3.2-Kodi
ERROR <general>: WARNING:root:## Resolving platform - system=linux, version=5.10.95, arch=x86, machine=aarch64
ERROR <general>: WARNING:root:## Resolved platform - system=linux, arch=armv7

INFO <general>: [plugin.video.torrest] Starting daemon with args: ('--port', '61235', '--settings', '/storage/.kodi/userdata/addon_data/plugin.video.torrest/settings.json')
INFO <general>: [plugin.video.torrest] Starting daemon logger
INFO <general>: [plugin.video.torrest] /storage/.kodi/userdata/addon_data/plugin.video.torrest/bin/torrest: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory


Starting Kodi (18.9 (18.9.0) Git:00ff7594e42e9539912c9bd12c5a6a9d1b9d8d78). Platform: Linux ARM 32-bit
NOTICE: Using Release Kodi x32 build
NOTICE: Kodi compiled 2021-09-07 by GCC 8.3.0 for Linux ARM 32-bit version 3.14.29 (200221)
NOTICE: Running on **CoreELEC** (official): 9.2.8, kernel: Linux ARM 64-bit version 3.14.29 aarch64
ERROR: WARNING:root:## Resolving platform - system=linux, version=3.14.29, arch=x86, machine=armv7l
ERROR: WARNING:root:## Resolved platform - system=linux, arch=armv7

NOTICE: [plugin.video.torrest] Starting daemon with args: ('--port', '61235', '--settings', u'/storage/.kodi/userdata/addon_data/plugin.video.torrest/settings.json')
NOTICE: [plugin.video.torrest] Starting daemon logger
NOTICE: [plugin.video.torrest] /storage/.kodi/userdata/addon_data/plugin.video.torrest/bin/torrest: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
```

**Comment by i96751414** [comment]
I will need some help to understand if libatomic is present or not on those OSs.
If it is not present, any chance they are installed for now (as a workaround)?

**Comment by lopezvg** [comment]
I have not found the way to check nor install a package in Libreelec.  It does not have any package magement.

**Comment by i96751414** [comment]
Can you connect via SSH?

**Comment by lopezvg** [comment]
Yes, I did, but Linux "apt" command, or similar, does not exist

**Comment by i96751414** [comment]
Can you do a find for atomic please?
`find / -name ”*atomic*"`

**Comment by lopezvg** [comment]
Sorry a busy day...

```
##############################################
#                 LibreELEC                  #
#            https://libreelec.tv            #
##############################################

LibreELEC (official): 10.0.2 (RPi4.arm)
RPI3:~ # find / -name "*atomic*"
/sys/kernel/tracing/events/nfs/nfs_atomic_open_enter
/sys/kernel/tracing/events/nfs/nfs_atomic_open_exit
/sys/kernel/debug/tracing/events/nfs/nfs_atomic_open_enter
/sys/kernel/debug/tracing/events/nfs/nfs_atomic_open_exit
/sys/fs/f2fs/features/atomic_write
RPI3:~ #
```

**Comment by i96751414** [comment]
No worries. Ok, I'll generate a few new binaries for you to test during the weekend.
In case you want to play around with it, you just need to add a case for linux-armv7 on https://github.com/i96751414/torrest-cpp/blob/master/docker/Makefile#L53

Then simply `make torrest-linux-armv7`

**Comment by lopezvg** [comment]
I have tried unsuccessfully.

- First with linux-arm*) OPTS="$${OPTS} -DCMAKE_EXE_LINKER_FLAGS='-static-libatomic'" ;; \  ==> script error: libatomic error
- Second with linux-arm*) OPTS="$${OPTS} -DCMAKE_EXE_LINKER_FLAGS='-static'" ;; \  ==> it built OK por linux-armv7, but gives execution error:
- RPI3:~/.kodi/userdata/addon_data/plugin.video.torrest/bin # ./torrest --port 61235 --settings /storage/.kodi/userdata/addon_d
ata/plugin.video.torrest/settings.json
2022-06-01 11:02:37.028 info [bittorrent] [thread-818] operation=configure, message='Applying session settings'
Segmentation fault

Maybe I'm doing something wrong...

**Comment by i96751414** [comment]
Can you try with -latomic?

**Comment by i96751414** [comment]
We might be setting them in the wrong place. Please try `-DCMAKE_CXX_FLAGS_RELEASE=-latomic`

**Comment by i96751414** [comment]
I think I got it:
[torrest.zip](https://github.com/i96751414/plugin.video.torrest/files/8818741/torrest.zip)

**Comment by lopezvg** [comment]
It works ok in both LibreElec and CoreElec, however there is a stange behaviour in managing Magnets that I need to test further. Downloads from magnets is increasingly important.

**Comment by i96751414** [comment]
What worker? My binary?
In regard to magnets, please open an issue in torrest-cpp project if you find a bug - I've tested and it worked so far.

**Comment by lopezvg** [comment]
Yes, your binary works
