### ISSUE TITLE
Show Torrest Downloading Percentage With My Addon

### ISSUE THREAD

**Issue by ponchofcult** [i96751414/plugin.video.torrest#22]
Hello, I am using the Torrest plugin to play torrent files with my addon. I would like to know how I can show the percentage of the current download to the users since I have no problem playing videos, but in the image section it tells me “No candidate files found” so I download them with: 

“plugin://plugin.video.torrest/torrents/{}/download”.format(info_hash) 

And to show the status I have tried in the same way with: “plugin://plugin.video.torrest/torrents/{}/torrent_status”.format(info_hash)

But nothing happens. I have tried to do it in several ways but it does not work. Is there any way to do it or is it impossible? Thank you for your help and for your excellent work.

**Comment by i96751414** [comment]
> but in the image section it tells me “No candidate files found” so I download them with:
> 
> “plugin://plugin.video.torrest/torrents/{}/download”.format(info_hash)

I didn't get what you mean with this. What image section are you mentioning?

Also, when you mean "show status" is it the download progress?

**Comment by ponchofcult** [comment]
> I didn't get what you mean with this. What image section are you mentioning?
> 

Sorry, it is a section of my addon that is Japanese music there are concerts, music videos, music among other things among those things there is a section of images of magazines and internet publications that come in Torrent and in another section subtitles that also come in Torrent. So what I'm doing is downloading the images, copying them to the folder that shows the addon to the user and the user already sees them. It's the easiest way I could think of to do it.

> Also, when you mean "show status" is it the download progress?

Yes, as inside the addon in the Torrents section in the context menu when you click on Torrent status you will see a progress dialog indicating the name of the Torrent, its status and percentage of download. That information is what I would like to show the user so that he knows how long it takes to download the images since some take less than 2 minutes to 5 minutes but some up to 30 minutes

**Comment by i96751414** [comment]
Ah! Now I understand. The play functions (play_magnet, play_url and play_path) were implemented to find videos (only) automatically:

https://github.com/i96751414/plugin.video.torrest/blob/ace42eadc22bcfdde5c8ddee4f71f61cf60007bb/lib/navigation.py#L306-L310

One could make a generic function that would play anything and if more than one file exists, it would list them and the user would have to choose.

Regarding the torrent status, you need to add it as an action to the context menu:

https://github.com/i96751414/plugin.video.torrest/blob/ace42eadc22bcfdde5c8ddee4f71f61cf60007bb/lib/navigation.py#L171

This will then add something like `RunPlugin(plugin.video.torrest://torrents/<info_hash>/torrent_status)`

**Comment by i96751414** [comment]
Closing this issue as it seems all questions were answered.
Feel free to submit a PR in case you desire a custom play function that suits your needs.

**Comment by ponchofcult** [comment]
Thank you very much, I'm sorry I'm still quite new doing this but thanks to you I learned to make contextual menus that I had not considered for my addons, I solved the previous problem for the moment only by activating the Show Background Progress option in Torrest settings now I only have one question But, is there a way to simply add a torrent to the torrent list with a call such as I imagine would be something like this: 

xbmc.executebuiltin('RunPlugin("plugin://plugin.video.torrest/add/torrent= path_to_my_file.torrent")') because I already tried it in several ways but I get:

 raise RoutingError('No route to path "%s"' % path)

 Is it possible? thank you so much!

**Comment by i96751414** [comment]
Hi. I'm glad you're learning with this project :)

Unfortunately there is no way to add a torrent simply because there is no route for such a method.
Adding that functionality to torrest would be trivial - you can submit PRs if you'd like.
