### ISSUE TITLE
Infinite “Buffering” with CoreELEC

### ISSUE THREAD

**Issue by mechalv** [i96751414/plugin.video.torrest#23]
Hi, I’m using CoreELEC 20.1 on an Amlogic s905x box. While using “Alfa” add-on, with last 0.0.14 version and this newer 0.0.15 version, the torrent pop-up window stays on “Buffering” forever, the torrents never start. Weeks ago I tried a 0.0.12 modified version that I found somewhere and worked once, not the next time.

I waited to share this problem until version 0.0.15 just in case the problem would be solved, but it does not seem to be the case.

I have limited knowledge, but I can give logs and/or try things that you propose.

Thanks in advance.
Regards.

**Comment by i96751414** [comment]
Thank you. I will have a look at this.

**Comment by i96751414** [comment]
I just had a very similar problem on an Android device and it happened to be related with the directory I had configured for downloads/torrents. Can you try a different directory?

**Comment by mechalv** [comment]
> I just had a very similar problem on an Android device and it happened to be related with the directory I had configured for downloads/torrents. Can you try a different directory?

Hi, you are right. I was using an external USB drive as a download folder. I have switched to a folder from the MicroSD from which I run the OS and works as it should. Is this something that can be solved?? The USB has R&W access. Thanks

**Comment by i96751414** [comment]
I believe this is related with some changes in libtorrent. I will try to understand what's causing the issue and apply a fix.

**Comment by lopezvg** [comment]
I believe it is related to this issue: on Android, Buffering stalls when using download path to external disks.  Tested with two tv-boxes with Android 9 and USB-3 high speed disks.  When I switched to internal memory, it started to work.

In background download it works with the external disks, although about half speed compared to the previous Torrest version.

**Comment by i96751414** [comment]
Previous versions were using libtorrent 1.2.x, this one is already using 2.x. I wonder if that is causing these issues, as the logic for storing pieces changed a lot in libtorrent 2.x.

**Comment by i96751414** [comment]
Closing this as it is being handled on #25.
