### ISSUE TITLE
Torrest 0.0.15 blows Kodi 18 on Android (and probably on Linux)

### ISSUE THREAD

**Issue by lopezvg** [i96751414/plugin.video.torrest#24]
It seems that the Libtorrest.so approach is not compatible with Kodi 18-Python 2.

I have tried replacing the /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.torrest/resources/bin/android_arm/libtorrest.so with the torrest.0.0.3.android_arm binary and it works.

[kodi.log](https://github.com/i96751414/plugin.video.torrest/files/11200034/kodi.log)

**Comment by i96751414** [comment]
Next torrest release will allow forcing to torrest binary on android devices.

**Comment by lopezvg** [comment]
I have tested it and it works fine, but inssuficient.  Since on
installation or first run you do not force automatically to Torrest binary
on Kodi 18, the user is facing a chicken and egg problem.  Kodi blows
BEFORE the user has time to access the setup to force the Torrest binary,
so the user is doomed.

For Alfa users, I hace setup a patch to change the Torrest setting.  The
first run manages to chage the setup xml, although still blows, but the
next run works fine.

Regards,
Alfa Group

**Comment by lopezvg** [comment]
In my case Kodi 18 updated automatically Torrest from verson 0.0.15 to 0.0.16.  It said that Torrest was updated but it did not ask to update the Torrest setting to set the to binary, so the next run Torrest assumed to use libtorrest.so and blowed after few seconds.  No chance to access the Torrest settings
