### ISSUE TITLE
Any way to 'bundle' this with an addon's repository?

### ISSUE THREAD

**Issue by pikdum** [i96751414/plugin.video.torrest#29]
Hello,

Is there a recommended way that I should include plugin.video.torrest in my repository?

Looking to add torrest support to my addon: https://github.com/pikdum/plugin.video.haru

For example, ResolveURL recommends doing this:

```xml
<dir>
    <info compressed="false">https://raw.githubusercontent.com/Gujal00/smrzips/master/addons.xml</info>
    <checksum>https://raw.githubusercontent.com/Gujal00/smrzips/master/addons.xml.md5</checksum>
    <datadir zip="true">https://raw.githubusercontent.com/Gujal00/smrzips/master/zips/</datadir>
</dir>
```

Would be neat if I could get things working without users needing to install it separately.

Thanks!

**Comment by i96751414** [comment]
Unfortunately torrest repository is more complex - it is not a static file.

I believe users will have to install my repository to have torrest support.
