### ISSUE TITLE
Torrest error, check log

### ISSUE THREAD

**Issue by Numeritxs** [i96751414/plugin.video.torrest#30]
Hi, I'm trying to install and use Torrest on a Fire TV Stick Basic Edition bought in 2018 and I'm getting an error just in this device. In a Fire TV Stick from 2021 it's working fine.

[﻿2023-10-13 171211.694 T14753    in.txt](https://github.com/i96751414/plugin.video.torrest/files/12895013/2023-10-13.171211.694.T14753.in.txt)

**Comment by i96751414** [comment]
The error you are having is due to the device having an old version of Android. I suggest you to force the torrest binary (instead of the library) in the addon settings.
