### ISSUE TITLE
Auto-delete Without Prompt

### ISSUE THREAD

**Issue by MrLatebros2** [i96751414/plugin.video.torrest#31]
Hello, and thank you for your work on this plugin. It is working well through the API with this:
https://github.com/theRedMercury/KODI-Popcorn-Time/tree/dev
running on OSMC on an RPi4.

In the config menu, I have enabled the "Ask to remove torrent after streaming" option, and it does work, but various family members forget to select 'yes' when the prompt appears.

This leads to already watched files accumulating on the Raspi's storage, which is a modest SD card, until no free space remains.

I would much appreciate a config option to auto delete files after streaming, without it having to prompt the user.
I suppose that it's similar code to the existing, but without a visible prompt, and the return value is always assumed as 'yes'.

I would attempt such a change myself, but I have little Github experience, so would likely break versioning.

Cheers for reading this. I realise that it's a minor issue, but would make all the difference in my use case.

**Comment by i96751414** [comment]
Hey!

I will add this in the next release ;)

Cheers.

**Comment by i96751414** [comment]
Closing this as it has been implemented.
