### ISSUE TITLE
Torrest hangs while download if I point paths to external USB dongle on my Cube gen3

### ISSUE THREAD

**Issue by puppinoo** [i96751414/plugin.video.torrest#33]
Hi,
Subject basically says all.
I inserted a USB dongle into my Fire TV Cube gen3 usb port.
After it's been recognized I pointed "Download path" and "Torrent folder" to something like: /Storage/USB id/Android/org.xbmc.kodi/ first and after I also tried /Storage/USB id/Android/org.xbmc.kodi/files/.
Torrest starts correctly but when I try to download anything, if the file is big, the buffer starts accumulating but suddenly hangs.
Not sure if the issue is related to the USB pointing but I cant try using internal storage cause it's very limited.
Sorry for wasting your time if I did anything wrong.

Regards.

**Comment by i96751414** [comment]
Hello,

Could you please have a look at https://github.com/i96751414/plugin.video.torrest/issues/25 ?

Can you also check if you are seeing multiple hash failed alerts?

**Comment by puppinoo** [comment]
Hi, sorry for being late but been busy with work.
I tested using adb for monitoring and I confirm
the torrent are being correctly downloaded into /storage/4028-1F23/Android/data/org.xbmc.kodi/files/torrents where 4028-1F23 is my usb dongle.
Unfortunately the log into /sdcard/Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.torrest/torrest.log is always 0 bytes so I was noit able to find anything useful.
I confirm the download starts correctly into the correct *external* folder but suddely hangs and speed lowers to 0b/s

Let me know if I can test better (maybe the log is into a different folder?)

Thanks.

**Comment by puppinoo** [comment]
Frankly mount output is very confusing so I paste the WHOLE output

`gazelle:/ $ mount 
/dev/root on / type ext4 (ro,seclabel,relatime)
tmpfs on /dev type tmpfs (rw,seclabel,nosuid,relatime,mode=755)
devpts on /dev/pts type devpts (rw,seclabel,relatime,mode=600,ptmxmode=000)
proc on /proc type proc (rw,relatime,gid=3009,hidepid=2)
sysfs on /sys type sysfs (rw,seclabel,relatime)
selinuxfs on /sys/fs/selinux type selinuxfs (rw,relatime)
tmpfs on /mnt type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000)
/dev/block/odm on /odm type ext4 (ro,seclabel,relatime,inode_readahead_blks=8)
/dev/block/dm-1 on /vendor type ext4 (ro,seclabel,relatime,inode_readahead_blks=8)
none on /acct type cgroup (rw,nosuid,nodev,noexec,relatime,cpuacct)
none on /dev/memcg type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
/sys/kernel/debug on /sys/kernel/debug type debugfs (rw,seclabel,relatime,mode=755)
configfs on /sys/kernel/config type configfs (rw,relatime)
none on /config type configfs (rw,nosuid,nodev,noexec,relatime)
none on /dev/cpuctl type cgroup (rw,nosuid,nodev,noexec,relatime,cpu)
none on /dev/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent)
cg2_bpf on /dev/cg2_bpf type cgroup2 (rw,nosuid,nodev,noexec,relatime)
none on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime)
pstore on /sys/fs/pstore type pstore (rw,seclabel,nosuid,nodev,noexec,relatime)
tmpfs on /dev/logd type tmpfs (rw,context=u:object_r:amz_logd_tmpfs:s0,relatime,size=512k,mode=770,uid=1036,gid=1036)
tmpfs on /vendor/lib/ms12 type tmpfs (ro,seclabel,relatime)
tracefs on /sys/kernel/debug/tracing type tracefs (rw,seclabel,relatime)
/dev/block/data on /data type ext4 (rw,seclabel,nosuid,nodev,noatime,discard,nodelalloc,resgid=1065,errors=panic)
/dev/block/cache on /cache type ext4 (rw,seclabel,nosuid,nodev,noatime,nodelalloc,errors=panic)
/dev/block/param on /mnt/vendor/param type ext4 (rw,seclabel,nosuid,nodev,noatime,nodelalloc,errors=panic)
tmpfs on /storage type tmpfs (rw,seclabel,nosuid,nodev,noexec,relatime,mode=755,gid=1000)
adb on /dev/usb-ffs/adb type functionfs (rw,relatime)
/dev/block/loop0 on /data/metrics type ext4 (rw,seclabel,noatime)
/data/media on /mnt/runtime/default/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal)
/data/media on /storage/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,multiuser,mask=6,derive_gid,default_normal)
/data/media on /mnt/runtime/read/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=23,derive_gid,default_normal)
/data/media on /mnt/runtime/write/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal)
/data/media on /mnt/runtime/full/emulated type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,multiuser,mask=7,derive_gid,default_normal)
/dev/block/vold/public:8,1 on /mnt/media_rw/4028-1F23 type vfat (rw,dirsync,nosuid,nodev,noexec,noatime,uid=1023,gid=1023,fmask=0007,dmask=0007,allow_utime=0020,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro)
/mnt/media_rw/4028-1F23 on /mnt/runtime/default/4028-1F23 type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=6)
/mnt/media_rw/4028-1F23 on /storage/4028-1F23 type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=6)
/mnt/media_rw/4028-1F23 on /mnt/runtime/read/4028-1F23 type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=18)
/mnt/media_rw/4028-1F23 on /mnt/runtime/write/4028-1F23 type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=9997,mask=18)
/mnt/media_rw/4028-1F23 on /mnt/runtime/full/4028-1F23 type sdcardfs (rw,nosuid,nodev,noexec,noatime,fsuid=1023,fsgid=1023,gid=1015,mask=7)
`

**Comment by puppinoo** [comment]
maybe this explains the issue
![Schermata del 2024-03-14 19-02-44](https://github.com/i96751414/plugin.video.torrest/assets/1208875/768b8d30-f3ce-4930-81cc-611a74bca44d)

**Comment by i96751414** [comment]
Can you please set all log levels to debug from within torrest settings and send me the torrest.log file? You can find it in plugin.video.torrest userdata.

**Comment by i96751414** [comment]
> maybe this explains the issue
> 
> https://www.aftvnews.com/fire-tv-stick-4k-max-fully-supports-external-usb-storage-with-ease/
> 
> ![Schermata del 2024-03-14 19-02-44](https://private-user-images.githubusercontent.com/1208875/312948850-768b8d30-f3ce-4930-81cc-611a74bca44d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2MTY2MjgsIm5iZiI6MTcxMDYxNjMyOCwicGF0aCI6Ii8xMjA4ODc1LzMxMjk0ODg1MC03NjhiOGQzMC1mM2NlLTQ5MzAtODFjYy02MTFhNzRiY2E0NGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTZUMTkxMjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2VmYzQ1M2EwNDg3MjAzY2NmZTIxMGVkNWRhYzIzZjU4ODk1N2JkODk4NzhmNzYzNzQ2ZmIyNGFiMDhhM2JkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.i9IQVH8JDWIqZtErIu_zngF_9iR4uB-xXp1-NGgm6jY)

Yes, that might be the problem. FAT32 supports a maximum of 4GB file size.

I would like to see torrest.log with all log levels set to debug tho, just to make sure I am not missing anything. You might have to close Kodi so its contents are flushed.

**Comment by puppinoo** [comment]
Hi, sorry for not responding earlier but work happened.
Since FS support on local FireOS is limited I decided to install server on my vps and use it remotely so I cant provide logs right now but I will try this weekend.
Thanks again for your amazing work and sorry again.
I have question about cleaning instalolation but I'll open another issue caus it's offtopic here.

Cheers.
