### ISSUE TITLE
cannot locate symbol "getifaddrs" with Torrest 0.0.18 on Android 6

### ISSUE THREAD

**Issue by lopezvg** [i96751414/plugin.video.torrest#37]
With OS Android 6.0.1 E2303 (no_rooted) (8x) aarch64 64-bit, Torrest 0.0.18 gives this error, both from library and from binary:

OSError: dlopen failed: cannot locate symbol "getifaddrs" referenced by "/data/data/org.xbmc.kodi/files/torrest/libtorrest.so"...
CANNOT LINK EXECUTABLE: cannot locate symbol "getifaddrs" referenced by "/data/data/org.xbmc.kodi/files/torrest/torrest"...

Same problem happens with OS Android 6.0.1 S12 (rooted) (8x) armv8l 32-bit

[SinLaOpcion.log](https://github.com/user-attachments/files/16191543/SinLaOpcion.log)
[ConLaOpcion.log](https://github.com/user-attachments/files/16191544/ConLaOpcion.log)

**Comment by i96751414** [comment]
This happens as the android toolchain is for API level 24, that is Android >= 7. This is required for libtorrent.

**Comment by i96751414** [comment]
Thanks, updated.
