### ISSUE TITLE
ConnectionError: HTTPConnectionPool

### ISSUE THREAD

**Issue by TitanKodi** [i96751414/plugin.video.torrest#4]
Hello when I try to enter the torrent section (previously with the torrent added from the file), I get this error, I had tried with 3 torrents and a url
 
```
13:49:26.779 T:24084   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.torrest/torrents
13:49:26.780 T:33500   ERROR: [plugin.video.torrest] Caught exception:
                                            Traceback (most recent call last):
                                              File "C:\Kodi\portable_data\addons\plugin.video.torrest\lib\navigation.py", line 393, in run
                                                plugin.run()
                                              File "C:\Kodi\portable_data\addons\script.module.routing\lib\routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "C:\Kodi\portable_data\addons\script.module.routing\lib\routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "C:\Kodi\portable_data\addons\plugin.video.torrest\lib\navigation.py", line 49, in wrapper
                                                raise e
                                            ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=61235): Max retries exceeded with url: /torrents?status=true (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x17118A10>: Failed to establish a new connection: [Errno 10061] No se puede establecer una conexi\xf3n ya que el equipo de destino deneg\xf3 expresamente dicha conexi\xf3n',))
```

**Comment by i96751414** [comment]
It seems torrest is not running on Kodi. Are you able to check if it is actually running? 
You can also enable debug on Kodi and send me the full logs (after a restart).

**Comment by TitanKodi** [comment]
> It seems torrest is not running on Kodi. Are you able to check if it is actually running?
> You can also enable debug on Kodi and send me the full logs (after a restart).

![image](https://user-images.githubusercontent.com/65163693/104033933-8026b580-51d0-11eb-8119-23e7cba3c462.png)

**Comment by TitanKodi** [comment]
Maybe is something that I do not doing good, I think I do not skip any step

**Comment by i96751414** [comment]
Please send me the full logs. Also, how have you installed the add-on?

**Comment by TitanKodi** [comment]
> Please send me the full logs. Also, how have you installed the add-on?

from the URL: `https://github.com/i96751414/plugin.video.torrest/archive/master.zip`

**Comment by i96751414** [comment]
That's the problem. You can't install it like that, otherwise the binary will not be available.
You need to get it from the releases section: https://github.com/i96751414/torrest/releases/latest.

**Comment by TitanKodi** [comment]
Ok, it works, two more things: there is a universal version? and in the future the plugin will work with Kodi 19?

**Comment by i96751414** [comment]
I have not produced a universal version as it was too heavy. But if you install it from the repository (https://github.com/i96751414/repository.github), it will automatically download the correct version for you.

Yes. It will work with Kodi 19 in the future.

**Comment by TitanKodi** [comment]
Ok, great, thanks for your plugin and for your time

> I have not produced a universal version as it was too heavy. But if you install it from the repository (https://github.com/i96751414/repository.github), it will automatically download the correct version for you.
> 
> Yes. It will work with Kodi 19 in the future.
